In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/con-test/con_test.csv
/kaggle/input/con-train/con_train.csv

In [2]:
df = pd.read_csv("/kaggle/input/con-train/con_train.csv")
df

,account_number,bad_flag,onus_attribute_1,transaction_attribute_1,transaction_attribute_2,transaction_attribute_3,transaction_attribute_4,transaction_attribute_5,transaction_attribute_6,transaction_attribute_7,...,bureau_enquiry_47,bureau_enquiry_48,bureau_enquiry_49,bureau_enquiry_50,onus_attribute_43,onus_attribute_44,onus_attribute_45,onus_attribute_46,onus_attribute_47,onus_attribute_48
0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2,0,221000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,0,25000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN
3,4,0,86000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,30.0,NaN,NaN,NaN,NaN,NaN,NaN
4,5,0,215000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96801,96802,0,156000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
96802,96803,0,46000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.0,0.0,1.0,0.0,1.0,0.0,0.0
96803,96804,0,95000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN
96804,96805,0,88000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN
96805,96806,0,94000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
test_df = pd.read_csv("/kaggle/input/con-test/con_test.csv")
test_df

,account_number,onus_attribute_1,transaction_attribute_1,transaction_attribute_2,transaction_attribute_3,transaction_attribute_4,transaction_attribute_5,transaction_attribute_6,transaction_attribute_7,transaction_attribute_8,...,bureau_enquiry_47,bureau_enquiry_48,bureau_enquiry_49,bureau_enquiry_50,onus_attribute_43,onus_attribute_44,onus_attribute_45,onus_attribute_46,onus_attribute_47,onus_attribute_48
0,100001,34000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,32.0,NaN,NaN,NaN,NaN,NaN,NaN
1,100002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,100003,130000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,0.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN
3,100004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,100005,53000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41787,141788,164000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN
41788,141789,68000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,19.0,0.0,1.0,0.0,1.0,0.0,0.0
41789,141790,155000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
41790,141791,99000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN
41791,141792,131000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96806 entries, 0 to 96805
Columns: 1216 entries, account_number to onus_attribute_48
dtypes: float64(1189), int64(27)
memory usage: 898.1 MB

In [5]:
df.describe()

,account_number,bad_flag,onus_attribute_1,transaction_attribute_1,transaction_attribute_2,transaction_attribute_3,transaction_attribute_4,transaction_attribute_5,transaction_attribute_6,transaction_attribute_7,...,bureau_enquiry_47,bureau_enquiry_48,bureau_enquiry_49,bureau_enquiry_50,onus_attribute_43,onus_attribute_44,onus_attribute_45,onus_attribute_46,onus_attribute_47,onus_attribute_48
count,96806.000000,96806.000000,7.157500e+04,71575.000000,71575.000000,71575.000000,71575.000000,71575.000000,71575.000000,71575.000000,...,94212.0,94212.000000,94212.000000,94212.000000,11610.000000,11610.000000,11610.000000,11610.000000,11610.000000,11610.000000
mean,48403.500000,0.014173,1.542391e+05,9.570769,0.002207,4.092854,77.306435,0.006315,67.043550,0.081034,...,0.0,0.189657,0.044283,7.800673,0.588114,1.497158,0.545650,1.430491,0.121447,0.119208
std,27945.629417,0.118203,1.729925e+05,1513.967595,0.119240,301.580599,3164.987013,0.129545,2516.330899,14.203615,...,0.0,0.597298,0.369451,8.655149,1.059613,1.702795,1.055865,1.728950,0.601256,0.599697
min,1.000000,0.000000,2.500000e+04,0.000000,0.000000,0.000000,-109800.476600,0.000000,-3498.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,24202.250000,0.000000,5.900000e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,2.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000
50%,48403.500000,0.000000,1.000000e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,5.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000
75%,72604.750000,0.000000,1.810000e+05,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,11.000000,1.000000,2.000000,1.000000,2.000000,0.000000,0.000000
max,96806.000000,1.000000,2.800000e+06,398936.791000,25.000000,55000.000000,358986.000000,12.000000,358986.000000,3150.000000,...,0.0,18.000000,14.000000,102.000000,19.000000,38.000000,19.000000,38.000000,15.000000,15.000000

In [6]:
nan_counts = df.isna().sum()
print(nan_counts)

account_number                 0
bad_flag                       0
onus_attribute_1           25231
transaction_attribute_1    25231
transaction_attribute_2    25231
                           ...
onus_attribute_44          85196
onus_attribute_45          85196
onus_attribute_46          85196
onus_attribute_47          85196
onus_attribute_48          85196
Length: 1216, dtype: int64

In [7]:
df.bad_flag.value_counts()

bad_flag
0    95434
1     1372
Name: count, dtype: int64

# Nan Value Handling

In [8]:
nan_counts = df.isna().sum()
high_nan = (nan_counts > 50000).sum()
print (high_nan)

19

In [9]:
import pandas as pd

# Example: Assuming 'data' is your DataFrame
nan_counts = df.isna().sum()  # Count NaN values in each column
columns_with_high_nan = nan_counts[nan_counts > 50000]  # Filter columns with NaN count > 50,000

# Print the results
print(f"Number of columns with more than 50,000 NaN values: {len(columns_with_high_nan)}")
print("Columns with more than 50,000 NaN values:")
print(columns_with_high_nan.index.tolist())

Number of columns with more than 50,000 NaN values: 19
Columns with more than 50,000 NaN values:
['bureau_148', 'bureau_433', 'bureau_435', 'bureau_436', 'bureau_437', 'bureau_438', 'bureau_444', 'bureau_445', 'bureau_446', 'bureau_447', 'bureau_448', 'bureau_449', 'bureau_451', 'onus_attribute_43', 'onus_attribute_44', 'onus_attribute_45', 'onus_attribute_46', 'onus_attribute_47', 'onus_attribute_48']

In [10]:
df = df.drop(['bureau_148', 'bureau_433', 'bureau_435', 'bureau_436', 'bureau_437', 'bureau_438', 'bureau_444', 'bureau_445', 'bureau_446', 'bureau_447', 'bureau_448', 'bureau_449', 'bureau_451', 'onus_attribute_43', 'onus_attribute_44', 'onus_attribute_45', 'onus_attribute_46', 'onus_attribute_47', 'onus_attribute_48'], axis = 1)
df

,account_number,bad_flag,onus_attribute_1,transaction_attribute_1,transaction_attribute_2,transaction_attribute_3,transaction_attribute_4,transaction_attribute_5,transaction_attribute_6,transaction_attribute_7,...,bureau_enquiry_41,bureau_enquiry_42,bureau_enquiry_43,bureau_enquiry_44,bureau_enquiry_45,bureau_enquiry_46,bureau_enquiry_47,bureau_enquiry_48,bureau_enquiry_49,bureau_enquiry_50
0,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2,0,221000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.0,2.0,4.0,0.0,1.0,0.0,0.0,0.0,2.0,3.0
2,3,0,25000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,11.0,0.0,11.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0
3,4,0,86000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,38.0,0.0,38.0,0.0,6.0,0.0,0.0,0.0,0.0,30.0
4,5,0,215000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96801,96802,0,156000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,0.0,5.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
96802,96803,0,46000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.0,0.0,5.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0
96803,96804,0,95000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,37.0,0.0,37.0,0.0,9.0,0.0,0.0,0.0,0.0,20.0
96804,96805,0,88000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.0,3.0,13.0,2.0,4.0,0.0,0.0,1.0,0.0,8.0
96805,96806,0,94000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,31.0,0.0,31.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0

In [11]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Ensure reproducibility
np.random.seed(42)

# Separate columns with numerical data (autoencoders work with numerical data only)
numerical_columns = df.select_dtypes(include=['float64', 'int64']).columns

# Scale the numerical data to [0, 1]
scaler =  MinMaxScaler()
scaled_data = scaler.fit_transform(df[numerical_columns])

# Replace NaNs with 0 temporarily for autoencoder training
# Autoencoders will learn to reconstruct the original data
nan_mask = np.isnan(scaled_data)  # Store the mask of NaN values
scaled_data[nan_mask] = 0

# Define the autoencoder
input_dim = scaled_data.shape[1]
autoencoder = Sequential([
    Dense(64, activation='relu', input_dim=input_dim),
    Dense(32, activation='relu'),
    Dense(64, activation='relu'),
    Dense(input_dim, activation='sigmoid')  # Output layer should match input dimension
])
autoencoder.compile(optimizer='adam', loss='mse')

# Train the autoencoder
autoencoder.fit(scaled_data, scaled_data, epochs=30, batch_size=32, verbose=1)

# Predict the reconstructed data
reconstructed_data = autoencoder.predict(scaled_data)

# Replace only the NaN values in the original scaled data
scaled_data[nan_mask] = reconstructed_data[nan_mask]

# Inverse transform the scaled data back to the original scale
imputed_data = scaler.inverse_transform(scaled_data)

# Update the original dataframe with imputed values
df_imputed = df.copy()
df_imputed[numerical_columns] = imputed_data

# Print a summary
print("NaN values successfully imputed using an autoencoder!")
print(df_imputed.head())

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - loss: 0.0169
Epoch 2/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 0.0022
Epoch 3/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 0.0016
Epoch 4/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 0.0014
Epoch 5/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 0.0012
Epoch 6/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 0.0011
Epoch 7/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 0.0011
Epoch 8/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 0.0010
Epoch 9/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 9.5021e-04
Epoch 10/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 9.0852e-04
Epoch 11/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 8.8680e-04
Epoch 12/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 8.5859e-04
Epoch 13/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 8.2864e-04
Epoch 14/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 8.1482e-04
Epoch 15/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 7.9169e-04
Epoch 16/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 7.9295e-04
Epoch 17/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 7.8214e-04
Epoch 18/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 7.6554e-04
Epoch 19/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 7.6149e-04
Epoch 20/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 7.5958e-04
Epoch 21/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 7.4931e-04
Epoch 22/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 7.4581e-04
Epoch 23/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 7.4015e-04
Epoch 24/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 7.2579e-04
Epoch 25/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 7.2253e-04
Epoch 26/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 7.2275e-04
Epoch 27/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 7.1462e-04
Epoch 28/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 7.1452e-04
Epoch 29/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 7.1584e-04
Epoch 30/30
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - loss: 7.0874e-04
3026/3026 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step
NaN values successfully imputed using an autoencoder!
   account_number  bad_flag  onus_attribute_1  transaction_attribute_1  \
0             1.0       0.0      28635.614947                 0.071679
1             2.0       0.0     221000.000000                 0.000000
2             3.0       0.0      25000.000000                 0.000000
3             4.0       0.0      86000.000000                 0.000000
4             5.0       0.0     215000.000000                 0.000000

   transaction_attribute_2  transaction_attribute_3  transaction_attribute_4  \
0                 0.000006                   0.2055            -106918.21656
1                 0.000000                   0.0000                  0.00000
2                 0.000000                   0.0000                  0.00000
3                 0.000000                   0.0000                  0.00000
4                 0.000000                   0.0000                  0.00000

   transaction_attribute_5  transaction_attribute_6  transaction_attribute_7  \
0                 0.002488             -3448.777748                 0.000578
1                 0.000000                 0.000000                 0.000000
2                 0.000000                 0.000000                 0.000000
3                 0.000000                 0.000000                 0.000000
4                 0.000000                 0.000000                 0.000000

   ...  bureau_enquiry_41  bureau_enquiry_42  bureau_enquiry_43  \
0  ...                3.0                0.0                3.0
1  ...                6.0                2.0                4.0
2  ...               11.0                0.0               11.0
3  ...               38.0                0.0               38.0
4  ...                1.0                0.0                1.0

   bureau_enquiry_44  bureau_enquiry_45  bureau_enquiry_46  bureau_enquiry_47  \
0                0.0                0.0                0.0                0.0
1                0.0                1.0                0.0                0.0
2                0.0                2.0                0.0                0.0
3                0.0                6.0                0.0                0.0
4                0.0                0.0                0.0                0.0

   bureau_enquiry_48  bureau_enquiry_49  bureau_enquiry_50
0                0.0                0.0                1.0
1                0.0                2.0                3.0
2                0.0                0.0                8.0
3                0.0                0.0               30.0
4                0.0                0.0                1.0

[5 rows x 1197 columns]

In [12]:
nan_counts = df_imputed.isna().sum()
print(nan_counts)

account_number             0
bad_flag                   0
onus_attribute_1           0
transaction_attribute_1    0
transaction_attribute_2    0
                          ..
bureau_enquiry_46          0
bureau_enquiry_47          0
bureau_enquiry_48          0
bureau_enquiry_49          0
bureau_enquiry_50          0
Length: 1197, dtype: int64

In [14]:
df_imputed

,account_number,bad_flag,onus_attribute_1,transaction_attribute_1,transaction_attribute_2,transaction_attribute_3,transaction_attribute_4,transaction_attribute_5,transaction_attribute_6,transaction_attribute_7,...,bureau_enquiry_41,bureau_enquiry_42,bureau_enquiry_43,bureau_enquiry_44,bureau_enquiry_45,bureau_enquiry_46,bureau_enquiry_47,bureau_enquiry_48,bureau_enquiry_49,bureau_enquiry_50
0,1.0,0.0,28635.614947,0.071679,0.000006,0.2055,-106918.21656,0.002488,-3448.777748,0.000578,...,3.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2.0,0.0,221000.000000,0.000000,0.000000,0.0000,0.00000,0.000000,0.000000,0.000000,...,6.0,2.0,4.0,0.0,1.0,0.0,0.0,0.0,2.0,3.0
2,3.0,0.0,25000.000000,0.000000,0.000000,0.0000,0.00000,0.000000,0.000000,0.000000,...,11.0,0.0,11.0,0.0,2.0,0.0,0.0,0.0,0.0,8.0
3,4.0,0.0,86000.000000,0.000000,0.000000,0.0000,0.00000,0.000000,0.000000,0.000000,...,38.0,0.0,38.0,0.0,6.0,0.0,0.0,0.0,0.0,30.0
4,5.0,0.0,215000.000000,0.000000,0.000000,0.0000,0.00000,0.000000,0.000000,0.000000,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96801,96802.0,0.0,156000.000000,0.000000,0.000000,0.0000,0.00000,0.000000,0.000000,0.000000,...,5.0,0.0,5.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
96802,96803.0,0.0,46000.000000,0.000000,0.000000,0.0000,0.00000,0.000000,0.000000,0.000000,...,5.0,0.0,5.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0
96803,96804.0,0.0,95000.000000,0.000000,0.000000,0.0000,0.00000,0.000000,0.000000,0.000000,...,37.0,0.0,37.0,0.0,9.0,0.0,0.0,0.0,0.0,20.0
96804,96805.0,0.0,88000.000000,0.000000,0.000000,0.0000,0.00000,0.000000,0.000000,0.000000,...,16.0,3.0,13.0,2.0,4.0,0.0,0.0,1.0,0.0,8.0
96805,96806.0,0.0,94000.000000,0.000000,0.000000,0.0000,0.00000,0.000000,0.000000,0.000000,...,31.0,0.0,31.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0

In [15]:
df_imputed.bad_flag.value_counts()

bad_flag
0.0    95434
1.0     1372
Name: count, dtype: int64

# Train-test Split

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X = df_imputed.drop(['account_number','bad_flag'], axis=1)
y = df_imputed['bad_flag']

In [18]:
from sklearn.preprocessing import MinMaxScaler

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Fit and transform the data
X_scaled = scaler.fit_transform(X)

# Convert back to a DataFrame (if X is a DataFrame)
# import pandas as pd
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

print("Data scaled using MinMaxScaler!")
print(X_scaled)

Data scaled using MinMaxScaler!
       onus_attribute_1  transaction_attribute_1  transaction_attribute_2  \
0              0.001310             1.796743e-07             2.232288e-07
1              0.070631             0.000000e+00             0.000000e+00
2              0.000000             0.000000e+00             0.000000e+00
3              0.021982             0.000000e+00             0.000000e+00
4              0.068468             0.000000e+00             0.000000e+00
...                 ...                      ...                      ...
96801          0.047207             0.000000e+00             0.000000e+00
96802          0.007568             0.000000e+00             0.000000e+00
96803          0.025225             0.000000e+00             0.000000e+00
96804          0.022703             0.000000e+00             0.000000e+00
96805          0.024865             0.000000e+00             0.000000e+00

       transaction_attribute_3  transaction_attribute_4  \
0                     0.000004                 0.006148
1                     0.000000                 0.234223
2                     0.000000                 0.234223
3                     0.000000                 0.234223
4                     0.000000                 0.234223
...                        ...                      ...
96801                 0.000000                 0.234223
96802                 0.000000                 0.234223
96803                 0.000000                 0.234223
96804                 0.000000                 0.234223
96805                 0.000000                 0.234223

       transaction_attribute_5  transaction_attribute_6  \
0                     0.000207                 0.000136
1                     0.000000                 0.009650
2                     0.000000                 0.009650
3                     0.000000                 0.009650
4                     0.000000                 0.009650
...                        ...                      ...
96801                 0.000000                 0.009650
96802                 0.000000                 0.009650
96803                 0.000000                 0.009650
96804                 0.000000                 0.009650
96805                 0.000000                 0.009650

       transaction_attribute_7  transaction_attribute_8  \
0                 1.835339e-07             4.421325e-07
1                 0.000000e+00             0.000000e+00
2                 0.000000e+00             0.000000e+00
3                 0.000000e+00             0.000000e+00
4                 0.000000e+00             0.000000e+00
...                        ...                      ...
96801             0.000000e+00             0.000000e+00
96802             0.000000e+00             0.000000e+00
96803             0.000000e+00             0.000000e+00
96804             0.000000e+00             0.000000e+00
96805             0.000000e+00             0.000000e+00

       transaction_attribute_9  ...  bureau_enquiry_41  bureau_enquiry_42  \
0                     0.000004  ...           0.010101           0.000000
1                     0.000000  ...           0.020202           0.033898
2                     0.000000  ...           0.037037           0.000000
3                     0.000000  ...           0.127946           0.000000
4                     0.000000  ...           0.003367           0.000000
...                        ...  ...                ...                ...
96801                 0.000000  ...           0.016835           0.000000
96802                 0.000000  ...           0.016835           0.000000
96803                 0.000000  ...           0.124579           0.000000
96804                 0.000000  ...           0.053872           0.050847
96805                 0.000000  ...           0.104377           0.000000

       bureau_enquiry_43  bureau_enquiry_44  bureau_enquiry_45  \
0               0.010453           0.000000           0.000000
1               0.013937           0.000000           0.007463
2               0.038328           0.000000           0.014925
3               0.132404           0.000000           0.044776
4               0.003484           0.000000           0.000000
...                  ...                ...                ...
96801           0.017422           0.000000           0.007463
96802           0.017422           0.000000           0.007463
96803           0.128920           0.000000           0.067164
96804           0.045296           0.083333           0.029851
96805           0.108014           0.000000           0.000000

       bureau_enquiry_46  bureau_enquiry_47  bureau_enquiry_48  \
0                    0.0                0.0           0.000000
1                    0.0                0.0           0.000000
2                    0.0                0.0           0.000000
3                    0.0                0.0           0.000000
4                    0.0                0.0           0.000000
...                  ...                ...                ...
96801                0.0                0.0           0.000000
96802                0.0                0.0           0.000000
96803                0.0                0.0           0.000000
96804                0.0                0.0           0.055556
96805                0.0                0.0           0.000000

       bureau_enquiry_49  bureau_enquiry_50
0               0.000000           0.009804
1               0.142857           0.029412
2               0.000000           0.078431
3               0.000000           0.294118
4               0.000000           0.009804
...                  ...                ...
96801           0.000000           0.009804
96802           0.000000           0.029412
96803           0.000000           0.196078
96804           0.000000           0.078431
96805           0.000000           0.245098

[96806 rows x 1195 columns]

In [19]:
X_train, X_val, y_train, y_val = train_test_split(X_scaled, y, test_size = 0.2,random_state=42)

In [20]:
print(X_train.shape, X_val.shape)

(77444, 1195) (19362, 1195)

In [64]:
X_train.describe()

,onus_attribute_1,transaction_attribute_1,transaction_attribute_2,transaction_attribute_3,transaction_attribute_4,transaction_attribute_5,transaction_attribute_6,transaction_attribute_7,transaction_attribute_8,transaction_attribute_9,...,bureau_enquiry_41,bureau_enquiry_42,bureau_enquiry_43,bureau_enquiry_44,bureau_enquiry_45,bureau_enquiry_46,bureau_enquiry_47,bureau_enquiry_48,bureau_enquiry_49,bureau_enquiry_50
count,77444.000000,7.744400e+04,7.744400e+04,7.744400e+04,77444.000000,7.744400e+04,77444.000000,7.744400e+04,7.744400e+04,7.744400e+04,...,77444.000000,77444.000000,77444.000000,77444.000000,77444.000000,77444.000000,77444.000000,77444.000000,77444.000000,77444.000000
mean,0.034592,1.225516e-05,5.983973e-05,5.303931e-05,0.174610,3.704069e-04,0.007325,2.190673e-05,1.663703e-05,2.586850e-05,...,0.051519,0.020449,0.049105,0.012655,0.026327,0.010338,0.004330,0.010274,0.003095,0.074819
std,0.057001,6.143520e-04,2.641925e-03,4.098789e-03,0.100940,8.945909e-03,0.006746,3.612812e-03,1.957895e-03,3.725093e-03,...,0.052677,0.036950,0.052591,0.037825,0.044105,0.028364,0.030344,0.032638,0.026078,0.084393
min,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000753,0.000000e+00,0.000000e+00,0.000000e+00,0.007854,0.000000e+00,0.000358,0.000000e+00,0.000000e+00,0.000000e+00,...,0.013468,0.000000,0.010453,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013689
50%,0.015856,0.000000e+00,0.000000e+00,0.000000e+00,0.234223,0.000000e+00,0.009650,0.000000e+00,0.000000e+00,0.000000e+00,...,0.037037,0.000000,0.031359,0.000000,0.007463,0.000000,0.000000,0.000000,0.000000,0.049020
75%,0.043243,1.749272e-07,9.715395e-07,5.215345e-07,0.234223,2.676193e-20,0.009650,1.389391e-07,4.056573e-07,9.792165e-07,...,0.074074,0.033898,0.069686,0.000000,0.037313,0.000000,0.000000,0.000000,0.000000,0.107843
max,1.000000,1.378665e-01,4.800000e-01,1.000000e+00,0.894890,7.500000e-01,0.782178,1.000000e+00,5.000000e-01,1.000000e+00,...,0.848485,1.000000,0.839721,1.000000,1.000000,1.000000,1.000000,0.888889,1.000000,1.000000

In [31]:
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Create the LightGBM dataset
train_data = lgb.Dataset(X_train, label=y_train)
val_data = lgb.Dataset(X_val, label=y_val, reference=train_data)

# Set random hyperparameters
params = {
    'objective': 'binary',          # Binary classification
    'boosting_type': 'gbdt',        # Gradient Boosting Decision Tree
    'metric': 'binary_error',       # Metric to evaluate performance (binary classification error)
    'learning_rate': 0.01,          # Step size shrinkage
    'num_leaves': 32,               # Maximum leaves in one tree
    'max_depth': 7,                # No limit on tree depth
    'min_data_in_leaf': 20,         # Minimum number of data points in a leaf
    'feature_fraction': 0.7,        # Fraction of features used per iteration
    'bagging_fraction': 0.7,        # Subsample ratio of data
    'bagging_freq': 5,              # Bagging frequency
    'verbose': -1                   # Suppress logs
}

# Train the model
model = lgb.train(
    params,
    train_data,
    valid_sets=[train_data, val_data],  # Validation for early stopping
    num_boost_round=1000              # Maximum number of boosting rounds           # Stop if validation score doesn't improve
)

# Predict probabilities on the validation set
y_pred_prob = model.predict(X_val)

# Convert probabilities to binary (0 or 1) based on a threshold of 0.5
y_pred = (y_pred_prob >= 0.5).astype(int)

# Evaluate the model using accuracy
accuracy = accuracy_score(y_val, y_pred)
print(f"Validation Accuracy: {accuracy:.4f}")

Validation Accuracy: 0.9889

In [39]:
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score

# Create the LightGBM dataset
train_data = lgb.Dataset(X_train, label=y_train)
val_data = lgb.Dataset(X_val, label=y_val, reference=train_data)

# Set random hyperparameters
params = {
        'objective': 'binary',          # Binary classification
    'boosting_type': 'gbdt',        # Gradient Boosting Decision Tree
    'metric': 'auc',       # Metric to evaluate performance (binary classification error)
    'learning_rate': 0.05,          # Step size shrinkage
    'num_leaves': 32,               # Maximum leaves in one tree
    'max_depth': -1,                # No limit on tree depth
    'min_data_in_leaf': 20,         # Minimum number of data points in a leaf
    'feature_fraction': 0.7,        # Fraction of features used per iteration
    'bagging_fraction': 0.7,        # Subsample ratio of data
    'bagging_freq': 5,              # Bagging frequency
    'verbose': -1,                  # Suppress logs
    'random_state': 42,               # Seed for reproducibility
    'device' : 'gpu'
}



# Train the model
model = lgb.train(
    params,
    train_data,
    valid_sets=[train_data, val_data],  # Validation for early stopping
    num_boost_round=1000              # Maximum number of boosting rounds
)

# Predict probabilities on the validation set
y_pred = model.predict(X_val)

# Evaluate the model
auc_score = roc_auc_score(y_val, y_pred)
print(f"Validation AUC: {auc_score:.4f}")

Validation AUC: 0.9082

In [32]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# Define the model
model = Sequential([
    Dense(128, activation='relu', input_dim=X_train.shape[1]),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(1, activation='sigmoid')  # Sigmoid for binary classification
])

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['AUC'])

# Early stopping to prevent overfitting
early_stopping = EarlyStopping(monitor='val_auc', patience=5, mode='max', restore_best_weights=True)

# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_val, y_val),
    epochs=50,
    batch_size=64,
    callbacks=[early_stopping],
    verbose=1
)

# Predict probabilities
y_pred_prob = model.predict(X_val)

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - AUC: 0.6306 - loss: 0.0934 - val_AUC: 0.7701 - val_loss: 0.0673
Epoch 2/50
 109/1211 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - AUC: 0.8222 - loss: 0.0584

/usr/local/lib/python3.10/dist-packages/keras/src/callbacks/early_stopping.py:155: UserWarning: Early stopping conditioned on metric `val_auc` which is not available. Available metrics are: AUC,loss,val_AUC,val_loss
  current = self.get_monitor_value(logs)

1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.7864 - loss: 0.0639 - val_AUC: 0.7827 - val_loss: 0.0656
Epoch 3/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.7924 - loss: 0.0691 - val_AUC: 0.7791 - val_loss: 0.0668
Epoch 4/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.8141 - loss: 0.0653 - val_AUC: 0.7875 - val_loss: 0.0659
Epoch 5/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.8270 - loss: 0.0644 - val_AUC: 0.7775 - val_loss: 0.0675
Epoch 6/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.8301 - loss: 0.0621 - val_AUC: 0.8058 - val_loss: 0.0649
Epoch 7/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.8331 - loss: 0.0631 - val_AUC: 0.8031 - val_loss: 0.0644
Epoch 8/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.8494 - loss: 0.0623 - val_AUC: 0.7911 - val_loss: 0.0655
Epoch 9/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.8573 - loss: 0.0583 - val_AUC: 0.8007 - val_loss: 0.0657
Epoch 10/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.8595 - loss: 0.0599 - val_AUC: 0.8121 - val_loss: 0.0649
Epoch 11/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.8596 - loss: 0.0581 - val_AUC: 0.8066 - val_loss: 0.0661
Epoch 12/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.8736 - loss: 0.0562 - val_AUC: 0.8092 - val_loss: 0.0662
Epoch 13/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.8809 - loss: 0.0546 - val_AUC: 0.8058 - val_loss: 0.0668
Epoch 14/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.8746 - loss: 0.0516 - val_AUC: 0.8067 - val_loss: 0.0685
Epoch 15/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.8792 - loss: 0.0544 - val_AUC: 0.8018 - val_loss: 0.0722
Epoch 16/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.8881 - loss: 0.0529 - val_AUC: 0.8028 - val_loss: 0.0717
Epoch 17/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9018 - loss: 0.0471 - val_AUC: 0.8135 - val_loss: 0.0693
Epoch 18/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.8865 - loss: 0.0515 - val_AUC: 0.8050 - val_loss: 0.0733
Epoch 19/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9009 - loss: 0.0523 - val_AUC: 0.8103 - val_loss: 0.0718
Epoch 20/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9037 - loss: 0.0497 - val_AUC: 0.7958 - val_loss: 0.0742
Epoch 21/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.8984 - loss: 0.0483 - val_AUC: 0.8008 - val_loss: 0.0777
Epoch 22/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9001 - loss: 0.0508 - val_AUC: 0.7958 - val_loss: 0.0795
Epoch 23/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9065 - loss: 0.0470 - val_AUC: 0.7894 - val_loss: 0.0813
Epoch 24/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9054 - loss: 0.0489 - val_AUC: 0.7971 - val_loss: 0.0826
Epoch 25/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9144 - loss: 0.0474 - val_AUC: 0.8113 - val_loss: 0.0803
Epoch 26/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9117 - loss: 0.0483 - val_AUC: 0.7919 - val_loss: 0.0836
Epoch 27/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9173 - loss: 0.0463 - val_AUC: 0.7858 - val_loss: 0.0896
Epoch 28/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9177 - loss: 0.0479 - val_AUC: 0.7916 - val_loss: 0.0906
Epoch 29/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9155 - loss: 0.0453 - val_AUC: 0.7891 - val_loss: 0.0934
Epoch 30/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9221 - loss: 0.0431 - val_AUC: 0.7763 - val_loss: 0.0970
Epoch 31/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9233 - loss: 0.0458 - val_AUC: 0.7828 - val_loss: 0.0962
Epoch 32/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9146 - loss: 0.0435 - val_AUC: 0.7837 - val_loss: 0.1002
Epoch 33/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9212 - loss: 0.0458 - val_AUC: 0.7829 - val_loss: 0.0992
Epoch 34/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9194 - loss: 0.0446 - val_AUC: 0.7660 - val_loss: 0.1049
Epoch 35/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9322 - loss: 0.0440 - val_AUC: 0.7678 - val_loss: 0.1054
Epoch 36/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9331 - loss: 0.0457 - val_AUC: 0.7699 - val_loss: 0.1080
Epoch 37/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9291 - loss: 0.0450 - val_AUC: 0.7705 - val_loss: 0.1034
Epoch 38/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9284 - loss: 0.0425 - val_AUC: 0.7632 - val_loss: 0.1177
Epoch 39/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9327 - loss: 0.0453 - val_AUC: 0.7637 - val_loss: 0.1036
Epoch 40/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9357 - loss: 0.0423 - val_AUC: 0.7697 - val_loss: 0.1080
Epoch 41/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9357 - loss: 0.0418 - val_AUC: 0.7514 - val_loss: 0.1243
Epoch 42/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9376 - loss: 0.0421 - val_AUC: 0.7635 - val_loss: 0.1190
Epoch 43/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9429 - loss: 0.0420 - val_AUC: 0.7589 - val_loss: 0.1162
Epoch 44/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9325 - loss: 0.0414 - val_AUC: 0.7667 - val_loss: 0.1169
Epoch 45/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9374 - loss: 0.0423 - val_AUC: 0.7594 - val_loss: 0.1193
Epoch 46/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9441 - loss: 0.0414 - val_AUC: 0.7492 - val_loss: 0.1362
Epoch 47/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9364 - loss: 0.0411 - val_AUC: 0.7593 - val_loss: 0.1299
Epoch 48/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9416 - loss: 0.0396 - val_AUC: 0.7573 - val_loss: 0.1340
Epoch 49/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9511 - loss: 0.0383 - val_AUC: 0.7534 - val_loss: 0.1346
Epoch 50/50
1211/1211 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - AUC: 0.9449 - loss: 0.0386 - val_AUC: 0.7359 - val_loss: 0.1604
606/606 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step